// <auto-generated />
using System;
using Avance_1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Avance_1.Migrations
{
    [DbContext(typeof(Avance_1Context))]
    partial class Avance_1ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Avance_1.Models.Agente", b =>
                {
                    b.Property<string>("IdAgente")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("PersonaId")
                        .IsRequired()
                        .HasColumnType("character varying(5)");

                    b.Property<string>("RolId")
                        .IsRequired()
                        .HasColumnType("character varying(5)");

                    b.HasKey("IdAgente");

                    b.HasIndex("PersonaId");

                    b.HasIndex("RolId");

                    b.ToTable("Agente");
                });

            modelBuilder.Entity("Avance_1.Models.CamECU911", b =>
                {
                    b.Property<string>("IdCam")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("IdZona")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("IdCam");

                    b.ToTable("CamECU911");
                });

            modelBuilder.Entity("Avance_1.Models.Persona", b =>
                {
                    b.Property<string>("IdPersona")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Fecha_nacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("IdPersona");

                    b.ToTable("Persona");
                });

            modelBuilder.Entity("Avance_1.Models.Roles", b =>
                {
                    b.Property<string>("IdRol")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nivel_privilegio")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Nombre_rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Avance_1.Models.Siniestro", b =>
                {
                    b.Property<string>("IdSiniestro")
                        .HasColumnType("text");

                    b.Property<string>("AgenteIdAgente")
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaSiniestro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdAgente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdZona")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NivelUrgencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZonaIdZona")
                        .IsRequired()
                        .HasColumnType("character varying(5)");

                    b.HasKey("IdSiniestro");

                    b.HasIndex("AgenteIdAgente");

                    b.HasIndex("ZonaIdZona");

                    b.ToTable("Siniestro");
                });

            modelBuilder.Entity("Avance_1.Models.Zona", b =>
                {
                    b.Property<string>("IdZona")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Descripcion_zona")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdZona");

                    b.ToTable("Zona");
                });

            modelBuilder.Entity("Avance_1.Models.Agente", b =>
                {
                    b.HasOne("Avance_1.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avance_1.Models.Roles", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Avance_1.Models.Siniestro", b =>
                {
                    b.HasOne("Avance_1.Models.Agente", "Agente")
                        .WithMany()
                        .HasForeignKey("AgenteIdAgente");

                    b.HasOne("Avance_1.Models.Zona", "Zona")
                        .WithMany()
                        .HasForeignKey("ZonaIdZona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agente");

                    b.Navigation("Zona");
                });
#pragma warning restore 612, 618
        }
    }
}
